### ISSUE TITLE
Why store router on zustand if router is already available via useRouter?

### ISSUE THREAD

**Issue by hems** [pmndrs/react-three-next#69] opened 2022-02-01 04:32 UTC
I'm curious about what's the advantage / goal of storing router on zustand if it's already available via `useRouter` ?

https://github.com/pmndrs/react-three-next/blob/8648c93e97ac9e2dc0fdfcb6b002eb3dd0418ca1/src/pages/_app.jsx#L26-L30

https://github.com/pmndrs/react-three-next/blob/8648c93e97ac9e2dc0fdfcb6b002eb3dd0418ca1/src/helpers/store.js#L5

https://github.com/pmndrs/react-three-next/blob/8648c93e97ac9e2dc0fdfcb6b002eb3dd0418ca1/src/components/canvas/Shader/Shader.jsx#L30

https://github.com/pmndrs/react-three-next/blob/8648c93e97ac9e2dc0fdfcb6b002eb3dd0418ca1/src/components/canvas/Box.jsx#L6

**Comment by marceloavf** [comment] 2022-02-03 13:02
I'm trying to reproduce a bug here, and I'm thinking that it's because of it.

If I use the router directly from next seems to bug some interactions because of R3F.

**Comment by RenaudRohlinger** [comment] 2022-02-05 01:57
Hello!

It is because[ context is lost through the reconciler](https://github.com/pmndrs/react-three-fiber/issues/114#issuecomment-501761003). So we have to either way forward it through [context bridge](https://docs.pmnd.rs/drei/misc/use-context-bridge) or via a state manager such as Zustand.

If that answers your question feel free to close this issue. Maybe we could add a small explanation in the readme

**Comment by hems** [comment] 2022-02-07 21:18
If you just import "Router" directly instead of "useRouter" won't that fix the issues?

i.e.

````ts
import Router from 'next/router'

Router.whateverYouNeed
````

**Comment by RenaudRohlinger** [comment] 2022-09-29 00:48
latest r3f fix this

**Closed by RenaudRohlinger** 2022-09-29 00:48 UTC
Labels: question

**Comment by synztran** [comment] 2024-08-15 10:47
> If you just import "Router" directly instead of "useRouter" won't that fix the issues?
> 
> i.e.
> 
> ```ts
> import Router from 'next/router'
> 
> Router.whateverYouNeed
> ```

It works. useRouter cannot be used. But the Router works.
