### ISSUE TITLE
"GenerateSW has been called multiple times" error when running in dev mode

### ISSUE THREAD

**Issue by claritise** [pmndrs/react-three-next#91] opened 2022-08-14 12:33 UTC
This is a fresh clone of the latest commit.
This also causes a service error when visiting the webpack server in the browser. 

![image](https://user-images.githubusercontent.com/20750968/184536994-53990bef-d06a-4041-a1a7-70a8a4db8d17.png)

```yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /Users/annazhang/git/3d-nft/3d-nft/node_modules/next-pwa/register.js
> [PWA] Service worker: /Users/annazhang/git/3d-nft/3d-nft/.next/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Build in develop mode, cache and precache are mostly disabled. This means offline support is disabled, but you can continue developing other functions in service worker.
> [PWA] Compile server
> [PWA] Compile server
event - compiled client and server successfully in 2.8s (1021 modules)
wait  - compiling / (client and server)...
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
wait  - compiling /404 (client and server)...
warn  - GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.```

**Comment by ydrea** [comment] 2022-08-21 09:21
same here!

**Comment by loganbutler** [comment] 2022-08-21 14:07
This error isn't too much of an issue, because when your code gets auto-updated in the browser it re-calls the function. aka, expected behavior. You wont see this error in a production mode, and the function will not be called multiple times. This only happens on your local env. 

The issue further down the pipe is the fact that the SW does not install at all for me, even in a production env because "the app does not work offline". I also had to copy the sw.js to the /public directory manually, to fix the 404 error in production env. I assume that would also fix your local issue, but thats hacky. Shouldn't have to copy that file anywhere. 

![image](https://user-images.githubusercontent.com/6056093/185794693-343ce505-f580-4265-95d6-ea7257b49068.png)

**Comment by juliocarneiro** [comment] 2022-08-31 13:45
> This error isn't too much of an issue, because when your code gets auto-updated in the browser it re-calls the function. aka, expected behavior. You wont see this error in a production mode, and the function will not be called multiple times. This only happens on your local env.
> 
> The issue further down the pipe is the fact that the SW does not install at all for me, even in a production env because "the app does not work offline". I also had to copy the sw.js to the /public directory manually, to fix the 404 error in production env. I assume that would also fix your local issue, but thats hacky. Shouldn't have to copy that file anywhere.
> 
> ![image](https://user-images.githubusercontent.com/6056093/185794693-343ce505-f580-4265-95d6-ea7257b49068.png)

copy the sw.js to the /public directory manually work for me!

**Comment by RenaudRohlinger** [comment] 2022-09-10 00:59
Thanks!

next-pwa was not up to date with the latest version of nextjs but everything should be fine now:
https://github.com/shadowwalker/next-pwa/commit/1e6af5fa9f6a807930f451adb5ab5078d5cda451#diff-38fcdef48d4c9636b640c40cb75b5278d405ab90f1b0960895900a068436f4cb

Please try again with a fresh install of react-three-next and close the issue if that fixes your problem :)

**Closed** 2023-05-06 05:51 UTC
